import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { Poppins } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Bonik | Welcome to Bonik",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased bg-gray-100 text-gray-900`}
      >
        <Providers>
          {/* Fixed Header */}
          <div className="fixed top-0 w-full z-50 shadow-md bg-white">
            <Header />
          </div>

          {/* Main Content */}
          <main className="pt-20 px-2 sm:px-0 lg:px-8 min-h-screen flex justify-center items-center">
            <div className="w-full">
              {children}
            </div>
          </main>


          {/* Toasts */}
          <ToastContainer position="top-right" autoClose={3000} />

          {/* Footer */}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
